# -*- coding: utf-8 -*-
"""Fuzzy_Conservative_Q_Learning_Cart_Pole_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QXT1N5e2pZ87ZXzRuiw9PVNnxINBluSj

Contained within this notebook is a sample implementation and demo of the proposed **Fuzzy Conservative Q-Learning** procedure. The code is not necessarily optimal or efficient with respect to performance, but was more or less written for interpretability. Some functions that may be difficult to follow, such as ECM, actually should have a one-to-one correspondence with the original paper's notation (in the case of ECM, that would be the dynamic evolving neuro fuzzy system called DENFIS).
"""

import os
import gym
import torch
import random
import warnings
import numpy as np

from soft.fuzzy.logic.control.tsk import MultiFLC as oldMultiFLC
from soft.fuzzy.logic.control.new_tsk import MultipleOutputFLC as newMultiFLC
from soft.fuzzy.logic.control.creation import self_organize as newScaffold

from scaffold import unsupervised as oldScaffold
from fcql import offline_q_learning
from d3rlpy.datasets import get_cartpole
from env_datasets import CartPoleDataset
from utils.reproducibility import env_seed
from sklearn.model_selection import train_test_split
from utils.metrics.offline.reinforcement.gym import evaluate_on_environment

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

"""
You can set the seed for reproducibility, 
define the number of maximum epochs to allow the agent to train, batch size, etc.

The antecedents or the fuzzy logic rules produced by the `unsupervised` function 
may change due to randomness (there may be more or less, they may behave differently, etc.). 

Note: You may need to do a fresh restart of the random number generators, environment, and so forth.
"""

SEED = 39  # used in the 'human-in-the-loop' example
MAX_EPOCHS = 12  # the maximum allowed number of epochs allowed for offline training
BATCH_SIZE = 64  # the number of training observations to sample from the data to perform a single update
CQL_ALPHA = 0.5  # the weight given to the CQL adjustment, a lower value is better when more data is available and vice versa
LEARNING_RATE = 1e-3  # the learning rate used in the paper, later, a better learning rate was found which was 3e-4
NUM_OF_TRAIN_EPISODES = 60  # the amount of training episodes that should be retrieved from CartPoleDataset to do offline training

if __name__ == "__main__":
    """Add reproducibility by setting the environment seed."""

    print('Using seed {}'.format(SEED))
    os.environ['PYTHONHASHSEED'] = str(SEED)
    torch.manual_seed(SEED)
    random.seed(SEED)
    np.random.seed(SEED)
    env = gym.make('CartPole-v1')
    env_seed(env, SEED)
    env.action_space.seed(SEED)

    # Number of states
    n_state = env.observation_space.shape[0]
    # Number of actions
    n_action = env.action_space.n

    seed_df = None

    print('num of epochs to be trained for: {}'.format(MAX_EPOCHS))

    """Apply Fuzzy Conservative Q-Learning algorithm to learn the Q-values."""
    dataset, _ = get_cartpole(dataset_type="replay")
    dataset = dataset[:1000]
    print('num of training episodes available: {}'.format(NUM_OF_TRAIN_EPISODES))
    # split train and test episodes
    train_episodes, val_episodes = train_test_split(dataset, test_size=0.2)
    train_episodes = train_episodes[:NUM_OF_TRAIN_EPISODES]

    train_data = CartPoleDataset(train_episodes)
    val_data = CartPoleDataset(val_episodes)

    # get replay results
    old_rules, _, old_antecedents = oldScaffold(train_data.unique_states, ecm=True, Dthr=4e-1)
    new_rules, new_antecedents = newScaffold(train_data.unique_states, val_data.unique_states,
                                             algorithms=('clip', 'ecm', 'wm-method'), Dthr=4e-1)

    print('There are {} rules'.format(len(old_rules)))

    for input_idx, input_variable in enumerate(old_antecedents):
        print('There are {} antecedent terms for the {}\'th input variable.'.format(len(input_variable), input_idx + 1))

    n_outputs = 2
    old_antecedents = []
    for var_idx, variable in enumerate(new_antecedents):
        old_antecedents.append([])
        for idx, center in enumerate(variable.centers.detach().numpy()):
            value = {'center': center, 'sigma': variable.sigmas[idx].item(), 'support': 1}
            old_antecedents[var_idx].append(value)

    from tests.fuzzy.logic.rules.wang_mendel import rule_creation as old_WM_method
    from soft.fuzzy.logic.rules.creation import wang_mendel_method as new_WM_method
    from soft.fuzzy.online.unsupervised.cluster.ecm import ECM as newECM
    from soft.fuzzy.online.unsupervised.granulation.clip import CLIP as newCLIP

    Dthr = 0.4
    new_clusters = newECM(train_data.unique_states, Dthr=Dthr)
    reduced_X = new_clusters.centers
    old_antecedents, old_rules, _ = old_WM_method(reduced_X.detach().numpy(), old_antecedents, [], [],
                                                  consistency_check=False)

    old_flc = oldMultiFLC(len(old_antecedents), n_outputs, old_antecedents, old_rules, learning_rate=LEARNING_RATE,
                          cql_alpha=CQL_ALPHA)
    try:
        # for input_idx, input_variable in enumerate(antecedents):
        #     print('There are {} antecedent terms for the {}\'th input variable.'.format(len(input_variable.centers),
        #                                                                                 input_idx + 1))

        n_outputs = 2
        new_flc = newMultiFLC(len(new_antecedents), n_outputs, new_antecedents, new_rules, learning_rate=LEARNING_RATE,
                              cql_alpha=CQL_ALPHA, input_trainable=False)

    except TypeError:
        n_outputs = 2
        new_flc = newMultiFLC(4, n_outputs, new_antecedents, new_rules, learning_rate=LEARNING_RATE,
                              cql_alpha=CQL_ALPHA, input_trainable=False)

    print(old_flc.flcs[0].input_terms.centers)
    print(old_flc.flcs[0].input_terms.sigmas)

    old_rules_matrix = np.array([rule['A'] for rule in old_rules])
    old_rules_matrix.sort()
    print(old_rules_matrix)
    new_rules_matrix = np.array([rule.antecedents for rule in new_rules])
    new_rules_matrix.sort()
    print(new_rules_matrix)

    assert old_rules_matrix.shape == new_rules_matrix.shape
    assert (old_rules_matrix == new_rules_matrix).all()
    assert (old_flc.flcs[0].links_between_antecedents_and_rules == new_flc.flcs[0].links_between_antecedents_and_rules).all()

    new_flc.flcs[0].input_granules.requires_grad_(False)
    # old_memberships = old_flc.flcs[0].input_terms(old_flc.flcs[0].transform(train_data.unique_states))
    # new_memberships = new_flc.flcs[0].input_granulation.granules(new_flc.flcs[0].transform(train_data.unique_states))
    # new_memberships = new_flc.flcs[0].input_granulation(torch.tensor(train_data.unique_states))

    # assert torch.isclose(old_memberships, new_memberships).all().item()

    old_flc, _, _ = offline_q_learning(old_flc, train_data, val_data, MAX_EPOCHS, BATCH_SIZE, gamma=0.99)

    print('--- NEW ---')
    new_flc, _, _ = offline_q_learning(new_flc, train_data, val_data, MAX_EPOCHS, BATCH_SIZE, gamma=0.99)

    print(old_flc.flcs[0].input_terms.centers)
    print(old_flc.flcs[0].input_terms.sigmas)
    print(old_flc.flcs[0].consequences)

    """Test your agent online! (this may take awhile if your agent is performing well)"""

    # evaluate
    print('old')
    summary_statistics = evaluate_on_environment(env, render=False)(old_flc)
    avg_score = summary_statistics.mean()
    std_score = summary_statistics.std()
    print((avg_score, std_score))
    print('new')
    summary_statistics = evaluate_on_environment(env, render=False)(new_flc)
    avg_score = summary_statistics.mean()
    std_score = summary_statistics.std()
    print((avg_score, std_score))
