# -*- coding: utf-8 -*-
"""Fuzzy_Conservative_Q_Learning_Cart_Pole_Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QXT1N5e2pZ87ZXzRuiw9PVNnxINBluSj

Contained within this notebook is a sample implementation and demo of the proposed **Fuzzy Conservative Q-Learning** procedure. The code is not necessarily optimal or efficient with respect to performance, but was more or less written for interpretability. Some functions that may be difficult to follow, such as ECM, actually should have a one-to-one correspondence with the original paper's notation (in the case of ECM, that would be the dynamic evolving neuro fuzzy system called DENFIS).
"""

import os
import gym
import torch
import random
import warnings
import numpy as np

from control import MultiFLC
from scaffold import unsupervised
from fcql import offline_q_learning
from d3rlpy.datasets import get_cartpole
from env_datasets import CartPoleDataset
from utils.reproducibility import env_seed
from sklearn.model_selection import train_test_split
from utils.metrics.offline.reinforcement.gym import evaluate_on_environment

warnings.filterwarnings("ignore", category=np.VisibleDeprecationWarning)

"""
You can set the seed for reproducibility, 
define the number of maximum epochs to allow the agent to train, batch size, etc.

The antecedents or the fuzzy logic rules produced by the `unsupervised` function 
may change due to randomness (there may be more or less, they may behave differently, etc.). 

Note: You may need to do a fresh restart of the random number generators, environment, and so forth.
"""

SEED = 39  # used in the 'human-in-the-loop' example
MAX_EPOCHS = 12  # the maximum allowed number of epochs allowed for offline training
BATCH_SIZE = 64  # the number of training observations to sample from the data to perform a single update
CQL_ALPHA = 0.5  # the weight given to the CQL adjustment, a lower value is better when more data is available and vice versa
LEARNING_RATE = 1e-3  # the learning rate used in the paper, later, a better learning rate was found which was 3e-4
NUM_OF_TRAIN_EPISODES = 60  # the amount of training episodes that should be retrieved from CartPoleDataset to do offline training

if __name__ == "__main__":
    """Add reproducibility by setting the environment seed."""

    print('Using seed {}'.format(SEED))
    os.environ['PYTHONHASHSEED'] = str(SEED)
    torch.manual_seed(SEED)
    random.seed(SEED)
    np.random.seed(SEED)
    env = gym.make('CartPole-v1')
    env_seed(env, SEED)
    env.action_space.seed(SEED)

    # Number of states
    n_state = env.observation_space.shape[0]
    # Number of actions
    n_action = env.action_space.n

    seed_df = None

    print('num of epochs to be trained for: {}'.format(MAX_EPOCHS))

    """Apply Fuzzy Conservative Q-Learning algorithm to learn the Q-values."""
    dataset, _ = get_cartpole(dataset_type="replay")
    dataset = dataset[:1000]
    print('num of training episodes available: {}'.format(NUM_OF_TRAIN_EPISODES))
    # split train and test episodes
    train_episodes, val_episodes = train_test_split(dataset, test_size=0.2)
    train_episodes = train_episodes[:NUM_OF_TRAIN_EPISODES]

    train_data = CartPoleDataset(train_episodes)
    val_data = CartPoleDataset(val_episodes)

    # get replay results
    rules, _, antecedents = unsupervised(train_data.unique_states, ecm=True, Dthr=4e-1)

    print('There are {} rules'.format(len(rules)))

    for input_idx, input_variable in enumerate(antecedents):
        print('There are {} antecedent terms for the {}\'th input variable.'.format(len(input_variable), input_idx + 1))

    n_outputs = 2
    flc = MultiFLC(len(antecedents), n_outputs, antecedents, rules, learning_rate=LEARNING_RATE, cql_alpha=CQL_ALPHA)

    print(flc.flcs[0].input_terms.centers)
    print(flc.flcs[0].input_terms.sigmas)

    flc, train_epoch_losses, val_epoch_losses = offline_q_learning(flc, train_data,
                                                                   val_data, MAX_EPOCHS,
                                                                   BATCH_SIZE,
                                                                   gamma=0.99)
    print(flc.flcs[0].input_terms.centers)
    print(flc.flcs[0].input_terms.sigmas)
    print(flc.flcs[0].consequences)

    """Test your agent online! (this may take awhile if your agent is performing well)"""

    # evaluate
    summary_statistics = evaluate_on_environment(env, render=False)(flc)
    avg_score = summary_statistics.mean()
    std_score = summary_statistics.std()
    print((avg_score, std_score))
